services:
  redis:
    image: redis
  rabbitmq:
    image: rabbitmq:management

  api-gateaway:
    image: ${DOCKER_REGISTRY-}yarpapigateaway
    build:
      context: .
      dockerfile: gateaway/YarpApiGateaway/Dockerfile

  userauth.api:
    image: ${DOCKER_REGISTRY-}userauthapi
    build:
      context: .
      dockerfile: microservices/UserAuth/UserAuth.API/Dockerfile
  userauth.api.migrations:
    image: ${DOCKER_REGISTRY-}userauthapi
    build:
      context: .
      dockerfile: microservices/UserAuth/UserAuth.API/Dockerfile
  


  order.api:
    image: ${DOCKER_REGISTRY-}orderapi
    build:
      context: .
      dockerfile: microservices/Order/Order.API/Dockerfile
  order.api.migrations:
    image: ${DOCKER_REGISTRY-}orderapi
    build:
      context: .
      dockerfile: microservices/Order/Order.API/Dockerfile
      


  admin.api:
    image: ${DOCKER_REGISTRY-}adminapi
    build:
      context: .
      dockerfile: monolithics/Admin/Admin.API/Dockerfile
  admin.api.migrations:
    image: ${DOCKER_REGISTRY-}adminapi
    build:
      context: .
      dockerfile: monolithics/Admin/Admin.API/Dockerfile

